"""
Phase 5F — deterministic, idempotent demo/base data for the Karmanya
backend.

Seeds BASE ENTITIES ONLY: one Federation, two Associations, the nine
Service rows both associations' workers need, four org-level Accounts
(Federation Admin, the two Association Admins, the demo User + its
UserProfile), and 215 Worker Accounts + Worker rows + WorkerSkill rows.
It deliberately does NOT seed ServiceRequest, Assignment, LeaveRequest,
Payment, Review, Notification, or any other lifecycle/booking data — that
is out of scope for this phase.

--------------------------------------------------------------------------
Admin dataset as source of truth
--------------------------------------------------------------------------
The 215 demo workers are NOT a second, independently authored dataset.
`admin/src/data/workerCatalog.ts` already generates the canonical 215
workers (120 "SKW-####" + 95 "GEN-####") from a small seeded PRNG
(`mulberry32`, seeds 20260914/20260915) — see that file for the original
TypeScript. `_generate_demo_workers()` below is a faithful, standalone
Python re-implementation of that exact algorithm (same constant pools,
same per-worker call order, same PRNG), so the two datasets are
guaranteed to agree without this backend ever importing or running any
TypeScript at seed time. This was verified this phase by running both
implementations side by side and diffing all 215 generated records
field-for-field (workerId, fullName, phoneNumber, address, pincode,
skills, rating, totalJobsCompleted, workerStatus) — zero mismatches.

Only identity/profile/skill fields are reproduced. `currentWorkload`,
`availabilityStatus`, `upcomingLeave`, and `currentAssignments` are
deliberately out of Phase 5F's locked scope and are never persisted here
-- but the PRNG calls those fields would have consumed in the original
generator ARE still replicated internally (see the comment inside
`_generate_workers_for_association`), because `workerStatus` (which we DO
need) is generated by the very last random() call for each worker, after
the calls those discarded fields would have made. Skipping those calls
would desynchronize the PRNG stream from `workerCatalog.ts` and silently
corrupt every worker generated after the first skipped one.

--------------------------------------------------------------------------
Admin skill -> backend Service mapping
--------------------------------------------------------------------------
The Admin generator's skill vocabulary (noun-form trade names) is mapped
onto this Phase 5F's locked, backend `Service.name` catalogue (see
`_SKILL_TO_SERVICE_NAME` below). `Service` is a global table (no
`association_id` column — see `app/models/service.py`); the same
`Service` row (e.g. "Plumbing") is intentionally shared by both
associations' workers via separate `WorkerSkill` rows, rather than being
duplicated per association.

--------------------------------------------------------------------------
Mukesh Yadav override
--------------------------------------------------------------------------
Worker `SKW-0066` is generated by the algorithm above as "Mukesh Yadav"
in the Skilled association with pincode 826004 -- already correct without
any change. Its `address`, `rating`, and `total_jobs_completed` do NOT
match the locked Phase 5F demo values on their own, so
`_MUKESH_OVERRIDE` explicitly overwrites exactly those three fields after
generation, before the row is written to the backend. This never touches
`admin/src/data/workerCatalog.ts` itself -- the override is applied only
to the backend's own copy of the data. `full_name` is intentionally not
part of the override (see "Worker full name / phone number" below);
`SKW-0066`'s `worker_code` is the only identity this script ever uses to
recognize the row, since a second worker ("SKW-0080") is independently
generated with the same name.

--------------------------------------------------------------------------
Worker full name / phone number
--------------------------------------------------------------------------
`Worker.full_name` (`String(255)`, **NOT NULL**) and `Worker.phone`
(`String(32)`, nullable) are existing columns on the current Worker
schema. `Worker.full_name` is populated from the Admin generator's
`fullName` (e.g. "Mukesh Yadav" for `SKW-0066`) and `Worker.phone` from
its `phoneNumber`, for every seeded worker -- `full_name` is required
simply because it is a `NOT NULL` column on the existing schema, not an
optional enhancement this script chose to add. No model change and no
migration were needed or made; both columns already existed before this
script was written.

--------------------------------------------------------------------------
Demo worker password convention (DEMO-ONLY)
--------------------------------------------------------------------------
Every seeded Worker Account's `login_id` is simply its `worker_code`
(e.g. "SKW-0066"), already guaranteed globally unique by the generator.
Its plaintext demo password is deterministically derived as
`f"{worker_code.lower().replace('-', '')}123"` (e.g. "skw0066123"),
mirroring the existing demo-account convention already used by
`admin/src/data/demoAccounts.ts` ("skilled123", "general123", "user123").
This is NOT a real authentication scheme -- it exists purely so a demo
worker login can be typed by hand -- and is always passed through
`app.auth.security.hash_password()` before storage; the plaintext value
is never persisted.

--------------------------------------------------------------------------
Fixed organization UUIDs
--------------------------------------------------------------------------
`Federation.name` and `Association.name` are NOT unique columns (confirmed
by reading both models), so a rerun of this script cannot safely
rediscover "the" demo Federation/Association by name alone -- a
coincidentally-same-named row created by someone else would be
indistinguishable from this script's own row. Instead, the three
singleton demo organization rows are looked up (and, on first run,
created) by a FIXED, deterministic UUID -- generated once via
`uuid.uuid5()` against a fixed local namespace + a stable label, so the
values are reproducible from this source file alone rather than being
inscrutable hardcoded literals. Explicitly supplying `id=` at
construction time is fully compatible with `Federation`/`Association` as
defined (`default=uuid.uuid4` is a Python-side default that only applies
when no value is supplied); no model/column change is needed or made.
If a row already exists at that fixed id but its name or federation
relationship doesn't match what this script expects, the script fails
loudly (`SeedIntegrityError`) rather than silently overwriting or
repurposing an unexpected row.

--------------------------------------------------------------------------
Development-database safety guard
--------------------------------------------------------------------------
See `_check_database_safety()`. Resolves `DATABASE_URL` via the existing
`app.config.get_settings()` (no hardcoded credentials anywhere), refuses
outright if the resolved database name contains "test" (this suite's
existing test databases are always named e.g. `karmanya_test`), and
otherwise requires an explicit `--yes-seed-development` CLI flag before
touching the resolved (real) database. No DB session is ever opened if
either check fails.

--------------------------------------------------------------------------
Usage
--------------------------------------------------------------------------
    python scripts/seed_demo_data.py --yes-seed-development

Idempotent: rerunning creates nothing new for entities that already
exist (recognized by their id/login_id/worker_code/name/composite key as
documented above) and reconciles their canonical demo field values,
without touching any row this script doesn't recognize as one of its
own.
"""

from __future__ import annotations

import argparse
import math
import sys
import uuid
from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent.parent
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from sqlalchemy import select  # noqa: E402
from sqlalchemy.engine import make_url  # noqa: E402
from sqlalchemy.orm import Session  # noqa: E402

from app.auth.security import hash_password, verify_password  # noqa: E402
from app.config import get_settings  # noqa: E402
from app.database import SessionLocal  # noqa: E402
from app.models import (  # noqa: E402
    Account,
    AccountRole,
    Association,
    Federation,
    Service,
    UserProfile,
    Worker,
    WorkerSkill,
    WorkerStatus,
)

# ==========================================================================
# Fixed demo identity constants
# ==========================================================================

# Fixed local namespace for this script's own uuid5-derived identities.
# An arbitrary, frozen constant -- never changes across runs/versions.
_DEMO_UUID_NAMESPACE = uuid.UUID("c5a1f9d2-6b3e-4a8f-9c2d-7e1b4f6a8d90")

FEDERATION_ID = uuid.uuid5(_DEMO_UUID_NAMESPACE, "phase5f:federation:karmanya")
ASSOCIATION_SKILLED_ID = uuid.uuid5(_DEMO_UUID_NAMESPACE, "phase5f:association:dhanbad_skilled")
ASSOCIATION_GENERAL_ID = uuid.uuid5(_DEMO_UUID_NAMESPACE, "phase5f:association:dhanbad_general")

FEDERATION_NAME = "Karmanya Federation Administration"
ASSOCIATION_SKILLED_NAME = "Dhanbad Skilled Workers Association"
ASSOCIATION_GENERAL_NAME = "Dhanbad General Workers Association"

# The nine backend Service rows both associations' WorkerSkill rows
# reference. Service is a global table (no association_id) -- see
# app/models/service.py -- so "Plumbing"/"Painting"/"General Helpers"
# are each a single shared row referenced by workers from both
# associations, not duplicated per association.
SERVICE_CATALOGUE: tuple[str, ...] = (
    "Plumbing",
    "Electrical",
    "Carpentry",
    "Masonry",
    "Painting",
    "Water Heater Technician",
    "General Helpers",
    "Cleaning",
    "Gardening",
)

# `Service.category` has no locked taxonomy anywhere in this codebase
# (confirmed: no Service rows exist in any production code path, and
# `shared/types/service.ts` types `category` as a plain `string` with no
# enum of values). Rather than inventing a multi-value taxonomy nothing
# else in the project defines, every seeded Service gets the same simple,
# deterministic category string -- accurate (all nine are home-service
# gig categories) and trivially stable across reruns.
_SERVICE_CATEGORY = "Home Services"

# Admin generator skill name -> locked Phase 5F backend Service.name.
_SKILL_TO_SERVICE_NAME: dict[str, str] = {
    "Plumber": "Plumbing",
    "Electrician": "Electrical",
    "Carpenter": "Carpentry",
    "Mason": "Masonry",
    "Painter": "Painting",
    "Cleaner": "Cleaning",
    "Gardener": "Gardening",
    "Helper": "General Helpers",
    "Water Heater Technician": "Water Heater Technician",
}

# Locked Phase 5F override for SKW-0066 ("Mukesh Yadav") -- applied only
# to this backend's own copy of the generated data, never to
# admin/src/data/workerCatalog.ts. worker_code is the only key used to
# find the row; a second, independently-generated "Mukesh Yadav" exists
# at SKW-0080 and must NOT be affected.
_MUKESH_WORKER_CODE = "SKW-0066"
_MUKESH_OVERRIDE = {
    "address": "House no. 108, Sector 4, Dhanbad, Jharkhand",
    "pincode": "826004",
    "rating": Decimal("4.80"),
    "total_jobs_completed": 42,
}


# ==========================================================================
# Deterministic Admin-generator port (identity/profile/skill fields only)
# ==========================================================================
#
# Faithful Python re-implementation of admin/src/data/workerCatalog.ts's
# `createSeededRandom` (mulberry32) + `generateWorkersForAssociation`.
# Verified this phase to produce byte-for-byte identical output to the
# original TypeScript for all 215 workers, across every field kept here.


def _imul32(a: int, b: int) -> int:
    """Port of JavaScript's `Math.imul` (32-bit integer multiply, low 32
    bits of the result, kept as an unsigned bit pattern)."""
    return (a * b) & 0xFFFFFFFF


def _create_seeded_random(seed: int):
    """
    Port of `createSeededRandom` (mulberry32) from
    admin/src/data/seededRandom.ts. `state`/`t` are always kept as plain
    non-negative 32-bit bit patterns (masked with `& 0xFFFFFFFF` after
    every operation) rather than converted to signed int32 -- every
    JavaScript operation the original uses (`^`, `|`, `>>>`, `Math.imul`)
    only cares about the underlying bit pattern, not its signed/unsigned
    interpretation, so this is equivalent without needing two's-complement
    bookkeeping.
    """
    state = seed & 0xFFFFFFFF

    def random() -> float:
        nonlocal state
        state = (state + 0x6D2B79F5) & 0xFFFFFFFF
        t1 = _imul32(state ^ (state >> 15), (1 | state) & 0xFFFFFFFF)
        inner = _imul32(t1 ^ (t1 >> 7), (61 | t1) & 0xFFFFFFFF)
        t2 = ((t1 + inner) ^ t1) & 0xFFFFFFFF
        result = (t2 ^ (t2 >> 14)) & 0xFFFFFFFF
        return result / 4294967296.0

    return random


def _pick(random, items):
    """Port of `pick()` -- always consumes exactly one random() call."""
    return items[math.floor(random() * len(items))]


def _int_between(random, lo: int, hi: int) -> int:
    """Port of `intBetween()` -- always consumes exactly one random() call."""
    return lo + math.floor(random() * (hi - lo + 1))


def _js_round(value: float) -> int:
    """
    Port of JavaScript's `Math.round` (rounds half towards +Infinity),
    which differs from Python's built-in `round()` (rounds half to even)
    at exact `.5` boundaries. Only used for `rating`.
    """
    return math.floor(value + 0.5)


_FIRST_NAMES = (
    "Rajesh", "Suresh", "Amit", "Vijay", "Sanjay", "Manoj", "Ramesh", "Ashok",
    "Dinesh", "Anil", "Prakash", "Sunil", "Rakesh", "Naresh", "Mahesh", "Deepak",
    "Vikram", "Ravi", "Sandeep", "Pankaj", "Arjun", "Rohit", "Vivek", "Alok",
    "Santosh", "Mukesh", "Yogesh", "Bimal", "Kamal", "Gopal", "Birsa", "Somra",
    "Sunita", "Rekha", "Kavita", "Pooja", "Anita", "Meena", "Geeta", "Sarita",
    "Nirmala", "Kiran", "Shanti", "Usha", "Lata", "Radha", "Sushma", "Manju",
)
_LAST_NAMES = (
    "Kumar", "Singh", "Sharma", "Verma", "Yadav", "Das", "Mahato", "Roy",
    "Prasad", "Thakur", "Mandal", "Hembrom", "Soren", "Oraon", "Mishra",
    "Choudhary", "Ram", "Gope", "Rana", "Sahu", "Turi", "Baski",
)
_COLONY_NAMES = (
    "Ambedkar Colony", "Ashok Nagar", "Vivekanand Colony", "Shastri Nagar",
    "Gandhi Colony", "Nehru Nagar", "Subhash Colony", "Model Colony",
    "Station Road Colony", "New Basti", "Ward 5 Colony", "Ward 9 Colony",
)
_PINCODES = ("826001", "826002", "826003", "826004", "826005")

# Only needed so the discarded currentAssignments loop below consumes the
# same NUMBER of random() calls as the original -- their content is
# otherwise irrelevant since none of it is persisted.
_ASSIGNMENT_TIME_SLOTS = ("9:00 AM", "10:00 AM", "11:00 AM", "1:00 PM", "2:00 PM", "4:00 PM", "6:00 PM")
_ASSIGNMENT_STATUSES = ("Scheduled", "In Progress")


@dataclass(frozen=True)
class _AssociationSeedConfig:
    slug: str
    skill_pool: tuple[str, ...]
    count: int
    id_prefix: str
    seed: int


_ASSOCIATION_SEEDS: tuple[_AssociationSeedConfig, ...] = (
    _AssociationSeedConfig(
        slug="dhanbad_skilled",
        skill_pool=("Plumber", "Electrician", "Carpenter", "Mason", "Painter", "Water Heater Technician", "Helper"),
        count=120,
        id_prefix="SKW",
        seed=20260914,
    ),
    _AssociationSeedConfig(
        slug="dhanbad_general",
        skill_pool=("Plumber", "Painter", "Cleaner", "Gardener", "Helper"),
        count=95,
        id_prefix="GEN",
        seed=20260915,
    ),
)


@dataclass(frozen=True)
class GeneratedWorker:
    """Identity/profile/skill fields for one demo worker, exactly as the
    Admin generator would produce them (before any Phase 5F override)."""

    worker_code: str
    association_slug: str
    full_name: str
    phone_number: str
    address: str
    pincode: str
    skills: tuple[str, ...]
    rating: float
    total_jobs_completed: int
    worker_status: str  # "Active" | "Inactive"


def _generate_workers_for_association(cfg: _AssociationSeedConfig) -> list[GeneratedWorker]:
    random = _create_seeded_random(cfg.seed)
    workers: list[GeneratedWorker] = []

    for i in range(cfg.count):
        worker_number = i + 1
        worker_code = f"{cfg.id_prefix}-{worker_number:04d}"

        full_name = f"{_pick(random, _FIRST_NAMES)} {_pick(random, _LAST_NAMES)}"

        primary_skill = cfg.skill_pool[i % len(cfg.skill_pool)]
        skills: list[str] = [primary_skill]
        extra_skill_count = _int_between(random, 0, 2)
        for _ in range(extra_skill_count):
            # Mirrors the original's `Set.add()`: consumes one random()
            # call per iteration regardless of whether the picked skill
            # was already present.
            candidate = _pick(random, cfg.skill_pool)
            if candidate not in skills:
                skills.append(candidate)

        house_number = _int_between(random, 1, 400)
        colony = _pick(random, _COLONY_NAMES)
        pincode = _pick(random, _PINCODES)
        address = f"House No. {house_number}, {colony}, Dhanbad, Jharkhand"

        association_block = 0 if cfg.id_prefix == "SKW" else 20000
        phone_number = f"+91-90000-{str(association_block + 10000 + worker_number)[-5:]}"

        rating = _js_round((4.0 + random() * 1.0) * 10) / 10
        total_jobs_completed = _int_between(random, 5, 260)

        # --- Everything below this point is OUT OF PHASE 5F SCOPE and is
        # never persisted -- but the calls themselves are kept exactly as
        # the original makes them, because `worker_status` (which we DO
        # need) is generated by the very last random() call for this
        # worker, after all of these. Skipping any of these calls would
        # desynchronize every subsequent worker's generated identity from
        # admin/src/data/workerCatalog.ts.
        availability_roll = random()
        if availability_roll < 0.6:
            availability_status = "Available"
        elif availability_roll < 0.85:
            availability_status = "Busy"
        else:
            availability_status = "Unavailable"

        leave_roll = random()
        if leave_roll < 0.12:
            _int_between(random, -3, 0)
            _int_between(random, 2, 6)
        elif leave_roll < 0.2:
            _int_between(random, 7, 30)
            _int_between(random, 2, 5)

        if availability_status == "Busy":
            current_workload = _int_between(random, 2, 6)
        elif availability_status == "Available":
            current_workload = _int_between(random, 0, 1)
        else:
            current_workload = 0

        for _ in range(current_workload):
            _pick(random, skills)
            _int_between(random, 0, 6)
            _pick(random, _ASSIGNMENT_TIME_SLOTS)
            _pick(random, _ASSIGNMENT_STATUSES)
        # --- end out-of-scope PRNG-synchronization block.

        worker_status = "Inactive" if random() < 0.05 else "Active"

        workers.append(
            GeneratedWorker(
                worker_code=worker_code,
                association_slug=cfg.slug,
                full_name=full_name,
                phone_number=phone_number,
                address=address,
                pincode=pincode,
                skills=tuple(skills),
                rating=rating,
                total_jobs_completed=total_jobs_completed,
                worker_status=worker_status,
            )
        )

    return workers


def _apply_mukesh_override(workers: list[GeneratedWorker]) -> list[GeneratedWorker]:
    """Overwrite exactly address/pincode/rating/total_jobs_completed for
    worker_code == SKW-0066, leaving every other worker (including the
    second "Mukesh Yadav" at SKW-0080) untouched."""
    result = []
    for worker in workers:
        if worker.worker_code == _MUKESH_WORKER_CODE:
            worker = GeneratedWorker(
                worker_code=worker.worker_code,
                association_slug=worker.association_slug,
                full_name=worker.full_name,
                phone_number=worker.phone_number,
                address=_MUKESH_OVERRIDE["address"],
                pincode=_MUKESH_OVERRIDE["pincode"],
                skills=worker.skills,
                rating=float(_MUKESH_OVERRIDE["rating"]),
                total_jobs_completed=_MUKESH_OVERRIDE["total_jobs_completed"],
                worker_status=worker.worker_status,
            )
        result.append(worker)
    return result


def generate_demo_workers() -> list[GeneratedWorker]:
    """The full, deterministic 215-worker dataset (120 Skilled + 95
    General), with the Mukesh Yadav override applied."""
    workers: list[GeneratedWorker] = []
    for cfg in _ASSOCIATION_SEEDS:
        workers.extend(_generate_workers_for_association(cfg))
    return _apply_mukesh_override(workers)


def _worker_password(worker_code: str) -> str:
    """DEMO-ONLY deterministic worker password -- see module docstring."""
    return f"{worker_code.lower().replace('-', '')}123"


def _worker_login_id(worker_code: str) -> str:
    return worker_code


# ==========================================================================
# Database safety guard
# ==========================================================================


class SeedSafetyError(Exception):
    """Raised when it is not safe to proceed with seeding."""


def _check_database_safety(database_url: str, *, allow_dev: bool) -> str:
    """
    Refuse to proceed unless it's safe to seed the resolved database.
    Returns the (non-secret) database name on success. Raises
    `SeedSafetyError` otherwise -- callers must not open a DB session if
    this raises.
    """
    db_name = make_url(database_url).database or "<unknown>"

    if "test" in db_name.lower():
        raise SeedSafetyError(
            f"Refusing to seed database '{db_name}': its name contains "
            "'test', which looks like this project's isolated test "
            "database (e.g. 'karmanya_test'). This script must never run "
            "against a test database."
        )

    if not allow_dev:
        raise SeedSafetyError(
            f"About to seed database '{db_name}'. Re-run with "
            "--yes-seed-development to confirm this is intentional."
        )

    return db_name


# ==========================================================================
# get_or_create / reconcile helpers
# ==========================================================================


class SeedIntegrityError(Exception):
    """Raised when an existing row at a fixed/known identity conflicts
    with what this script expects -- never silently repurposed."""


def _get_or_create_federation(session: Session) -> Federation:
    federation = session.get(Federation, FEDERATION_ID)
    if federation is None:
        federation = Federation(id=FEDERATION_ID, name=FEDERATION_NAME)
        session.add(federation)
        return federation
    if federation.name != FEDERATION_NAME:
        raise SeedIntegrityError(
            f"Federation {FEDERATION_ID} already exists with name "
            f"{federation.name!r}, expected {FEDERATION_NAME!r}. Refusing "
            "to silently repurpose it."
        )
    return federation


def _get_or_create_association(
    session: Session, *, association_id: uuid.UUID, name: str, federation_id: uuid.UUID
) -> Association:
    association = session.get(Association, association_id)
    if association is None:
        association = Association(id=association_id, name=name, federation_id=federation_id)
        session.add(association)
        return association
    if association.name != name or association.federation_id != federation_id:
        raise SeedIntegrityError(
            f"Association {association_id} already exists as "
            f"(name={association.name!r}, federation_id={association.federation_id}), "
            f"expected (name={name!r}, federation_id={federation_id}). Refusing to "
            "silently repurpose it."
        )
    return association


def _get_or_create_service(session: Session, name: str) -> Service:
    service = session.execute(select(Service).where(Service.name == name)).scalar_one_or_none()
    if service is None:
        service = Service(name=name, category=_SERVICE_CATEGORY, is_active=True)
        session.add(service)
        return service
    # Reconcile only the fields this script owns for its own known
    # services -- never touches any other Service row.
    service.category = _SERVICE_CATEGORY
    service.is_active = True
    return service


def _get_or_create_org_account(
    session: Session,
    *,
    login_id: str,
    password: str,
    role: AccountRole,
    association_id: uuid.UUID | None,
    federation_id: uuid.UUID | None,
) -> Account:
    account = session.execute(select(Account).where(Account.login_id == login_id)).scalar_one_or_none()
    if account is None:
        account = Account(
            id=uuid.uuid4(),
            login_id=login_id,
            role=role,
            password_hash=hash_password(password),
            association_id=association_id,
            federation_id=federation_id,
            is_active=True,
        )
        session.add(account)
        return account
    # Reconcile canonical demo values on rerun (restores drift, e.g. a
    # role/scope change). Password hash restoration: verify the canonical
    # plaintext password against whatever hash is already stored, and
    # only compute + store a fresh hash if that verification fails (or no
    # hash exists at all). This means a normal rerun where nothing
    # drifted leaves the stored hash string byte-for-byte unchanged
    # (nothing is rewritten), while an account whose hash was deliberately
    # replaced with something else gets the canonical demo password
    # restored on the next run -- using the project's own
    # `hash_password`/`verify_password` helpers, never a hand-rolled
    # comparison.
    account.role = role
    if not account.password_hash or not verify_password(password, account.password_hash):
        account.password_hash = hash_password(password)
    account.association_id = association_id
    account.federation_id = federation_id
    account.is_active = True
    return account


def _get_or_create_user_profile(session: Session, account: Account, *, full_name: str) -> UserProfile:
    profile = session.execute(
        select(UserProfile).where(UserProfile.account_id == account.id)
    ).scalar_one_or_none()
    if profile is None:
        profile = UserProfile(id=uuid.uuid4(), account_id=account.id, full_name=full_name, phone=None)
        session.add(profile)
        return profile
    profile.full_name = full_name
    return profile


def _get_or_create_worker_account(session: Session, generated: GeneratedWorker, association_id: uuid.UUID) -> Account:
    login_id = _worker_login_id(generated.worker_code)
    return _get_or_create_org_account(
        session,
        login_id=login_id,
        password=_worker_password(generated.worker_code),
        role=AccountRole.WORKER,
        association_id=association_id,
        federation_id=None,
    )


def _get_or_create_worker(
    session: Session, *, account: Account, association_id: uuid.UUID, generated: GeneratedWorker
) -> Worker:
    worker = session.execute(
        select(Worker).where(Worker.worker_code == generated.worker_code)
    ).scalar_one_or_none()
    status = WorkerStatus.INACTIVE if generated.worker_status == "Inactive" else WorkerStatus.ACTIVE
    rating = Decimal(str(generated.rating))
    if worker is None:
        worker = Worker(
            id=uuid.uuid4(),
            account_id=account.id,
            association_id=association_id,
            worker_code=generated.worker_code,
            full_name=generated.full_name,
            phone=generated.phone_number,
            address=generated.address,
            pincode=generated.pincode,
            rating=rating,
            total_jobs_completed=generated.total_jobs_completed,
            status=status,
        )
        session.add(worker)
        return worker
    # Reconcile canonical demo values on rerun (this is exactly how the
    # Mukesh Yadav override is restored if a prior run's row drifted).
    worker.account_id = account.id
    worker.association_id = association_id
    worker.full_name = generated.full_name
    worker.phone = generated.phone_number
    worker.address = generated.address
    worker.pincode = generated.pincode
    worker.rating = rating
    worker.total_jobs_completed = generated.total_jobs_completed
    worker.status = status
    return worker


def _ensure_worker_skill(session: Session, *, worker_id: uuid.UUID, service_id: uuid.UUID) -> None:
    existing = session.execute(
        select(WorkerSkill).where(
            WorkerSkill.worker_id == worker_id, WorkerSkill.service_id == service_id
        )
    ).scalar_one_or_none()
    if existing is None:
        session.add(WorkerSkill(worker_id=worker_id, service_id=service_id))


# ==========================================================================
# Validation (run before the final commit)
# ==========================================================================


class SeedValidationError(Exception):
    """Raised with every failed validation check joined together."""


def validate_seed(session: Session, generated_workers: list[GeneratedWorker]) -> None:
    """
    Ownership-based validation: confirms every canonical demo entity this
    script owns exists with the expected values. Deliberately does NOT
    assert anything about the database's TOTAL row counts (e.g. "exactly
    215 Worker rows exist") -- the development database may legitimately
    contain other, non-demo workers/accounts/services alongside these,
    and validation must not fail just because it does. Every check below
    looks up a specific, known canonical row (by worker_code/login_id/
    service name/fixed UUID) and checks its values; it never scans "all
    rows of table X" and compares the count to an expected total.
    """
    problems: list[str] = []

    federation = session.get(Federation, FEDERATION_ID)
    if federation is None or federation.name != FEDERATION_NAME:
        problems.append("Federation row missing or incorrect.")

    assoc_skilled = session.get(Association, ASSOCIATION_SKILLED_ID)
    if assoc_skilled is None or assoc_skilled.name != ASSOCIATION_SKILLED_NAME:
        problems.append("Skilled Association row missing or incorrect.")
    assoc_general = session.get(Association, ASSOCIATION_GENERAL_ID)
    if assoc_general is None or assoc_general.name != ASSOCIATION_GENERAL_NAME:
        problems.append("General Association row missing or incorrect.")

    # Only checks that these nine specific, named Service rows exist and
    # are active -- never asserts that the `services` table contains only
    # these nine.
    services = {
        s.name: s
        for s in session.execute(
            select(Service).where(Service.name.in_(SERVICE_CATALOGUE))
        ).scalars()
    }
    missing_services = set(SERVICE_CATALOGUE) - set(services)
    if missing_services:
        problems.append(f"Missing Service rows: {sorted(missing_services)}")
    for name, service in services.items():
        if not service.is_active:
            problems.append(f"Service {name!r} is not active.")

    for login_id, expected_role in (
        ("federation_admin", AccountRole.FEDERATION_ADMIN),
        ("dhanbad_skilled", AccountRole.ASSOCIATION_ADMIN),
        ("dhanbad_general", AccountRole.ASSOCIATION_ADMIN),
        ("demo_user", AccountRole.USER),
    ):
        account = session.execute(select(Account).where(Account.login_id == login_id)).scalar_one_or_none()
        if account is None or account.role != expected_role:
            problems.append(f"Account {login_id!r} missing or has wrong role.")

    # Canonical worker_codes only -- looked up by name, not "every Worker
    # row in the table". A Worker row this script doesn't recognize is
    # simply never touched by any of this.
    expected_codes = [w.worker_code for w in generated_workers]
    canonical_workers = {
        w.worker_code: w
        for w in session.execute(
            select(Worker).where(Worker.worker_code.in_(expected_codes))
        ).scalars()
    }
    missing_codes = set(expected_codes) - set(canonical_workers)
    if missing_codes:
        problems.append(f"{len(missing_codes)} canonical worker(s) missing, e.g. {sorted(missing_codes)[:5]}.")

    skilled_count = sum(
        1 for w in canonical_workers.values() if w.association_id == ASSOCIATION_SKILLED_ID
    )
    general_count = sum(
        1 for w in canonical_workers.values() if w.association_id == ASSOCIATION_GENERAL_ID
    )
    if skilled_count != 120:
        problems.append(f"Expected 120 canonical Skilled workers, found {skilled_count}.")
    if general_count != 95:
        problems.append(f"Expected 95 canonical General workers, found {general_count}.")

    # Canonical worker accounts (by login_id == worker_code) -- again,
    # never "every Account with role WORKER in the table".
    canonical_worker_accounts = {
        a.login_id: a
        for a in session.execute(
            select(Account).where(Account.login_id.in_(expected_codes))
        ).scalars()
    }

    association_id_by_slug = {
        "dhanbad_skilled": ASSOCIATION_SKILLED_ID,
        "dhanbad_general": ASSOCIATION_GENERAL_ID,
    }
    skill_rows_by_worker_id: dict[uuid.UUID, set[uuid.UUID]] = {}
    if canonical_workers:
        for row in session.execute(
            select(WorkerSkill).where(
                WorkerSkill.worker_id.in_([w.id for w in canonical_workers.values()])
            )
        ).scalars():
            skill_rows_by_worker_id.setdefault(row.worker_id, set()).add(row.service_id)

    service_ids_by_name = {name: svc.id for name, svc in services.items()}
    services_used_by_canonical_workers: set[uuid.UUID] = set()

    for generated in generated_workers:
        worker = canonical_workers.get(generated.worker_code)
        if worker is None:
            continue  # already reported as missing above

        expected_association_id = association_id_by_slug[generated.association_slug]
        if worker.association_id != expected_association_id:
            problems.append(f"Worker {generated.worker_code} is not in the expected association.")
        if not worker.full_name:
            problems.append(f"Worker {generated.worker_code} has an empty full_name.")
        elif worker.full_name != generated.full_name:
            problems.append(f"Worker {generated.worker_code} full_name does not match the generator.")
        if worker.phone != generated.phone_number:
            problems.append(f"Worker {generated.worker_code} phone does not match the generator.")
        # NOTE: `generated` here is an element of `generated_workers`,
        # which already has `_apply_mukesh_override()` applied (see
        # `generate_demo_workers()`) -- so for SKW-0066, `generated.address`
        # /`.pincode`/`.rating`/`.total_jobs_completed` already ARE the
        # override values, and comparing against `generated.*` directly
        # (rather than branching on worker_code again here) checks the
        # override for free, for every worker in one pass.
        if worker.address != generated.address:
            problems.append(f"Worker {generated.worker_code} address does not match the expected value.")
        if worker.pincode != generated.pincode:
            problems.append(f"Worker {generated.worker_code} pincode does not match the expected value.")
        if worker.rating != Decimal(str(generated.rating)):
            problems.append(f"Worker {generated.worker_code} rating does not match the expected value.")
        if worker.total_jobs_completed != generated.total_jobs_completed:
            problems.append(f"Worker {generated.worker_code} total_jobs_completed does not match the expected value.")
        expected_status = WorkerStatus.INACTIVE if generated.worker_status == "Inactive" else WorkerStatus.ACTIVE
        if worker.status != expected_status:
            problems.append(f"Worker {generated.worker_code} status does not match the generator.")

        account = canonical_worker_accounts.get(generated.worker_code)
        if account is None or account.role != AccountRole.WORKER:
            problems.append(f"Worker {generated.worker_code} has no valid WORKER account.")
        else:
            if account.association_id != worker.association_id:
                problems.append(f"Worker {generated.worker_code} account/worker association mismatch.")
            if account.federation_id is not None:
                problems.append(f"Worker {generated.worker_code} account has a non-null federation_id.")

        expected_service_ids = set()
        for admin_skill in generated.skills:
            service_name = _SKILL_TO_SERVICE_NAME[admin_skill]
            service_id = service_ids_by_name.get(service_name)
            if service_id is None:
                problems.append(f"Service {service_name!r} (needed by {generated.worker_code}) is missing.")
                continue
            expected_service_ids.add(service_id)
        actual_service_ids = skill_rows_by_worker_id.get(worker.id, set())
        missing_skills = expected_service_ids - actual_service_ids
        if missing_skills:
            problems.append(f"Worker {generated.worker_code} is missing {len(missing_skills)} expected WorkerSkill row(s).")
        services_used_by_canonical_workers |= actual_service_ids & expected_service_ids

    # Every canonical service must be used by at least one canonical
    # worker -- computed only from the canonical workers/skills gathered
    # above, never from "every WorkerSkill row in the table".
    for name, service_id in service_ids_by_name.items():
        if service_id not in services_used_by_canonical_workers:
            problems.append(f"Service {name!r} has zero canonical workers.")

    # Mukesh Yadav override -- exact values, by worker_code only.
    mukesh_generated = next((w for w in generated_workers if w.worker_code == _MUKESH_WORKER_CODE), None)
    if mukesh_generated is None or mukesh_generated.full_name != "Mukesh Yadav":
        problems.append("Generated SKW-0066 identity is not 'Mukesh Yadav' -- generator port drifted.")
    mukesh_worker = canonical_workers.get(_MUKESH_WORKER_CODE)
    if mukesh_worker is None:
        problems.append("SKW-0066 Worker row missing.")
    else:
        if mukesh_worker.association_id != ASSOCIATION_SKILLED_ID:
            problems.append("SKW-0066 is not in the Skilled association.")
        if mukesh_worker.full_name != "Mukesh Yadav":
            problems.append(f"SKW-0066 full_name is {mukesh_worker.full_name!r}, expected 'Mukesh Yadav'.")
        if mukesh_generated is not None and mukesh_worker.phone != mukesh_generated.phone_number:
            problems.append("SKW-0066 phone does not match the generator's phoneNumber.")
        if mukesh_worker.address != _MUKESH_OVERRIDE["address"]:
            problems.append("SKW-0066 address override not applied.")
        if mukesh_worker.pincode != _MUKESH_OVERRIDE["pincode"]:
            problems.append("SKW-0066 pincode override not applied.")
        if mukesh_worker.rating != _MUKESH_OVERRIDE["rating"]:
            problems.append(f"SKW-0066 rating is {mukesh_worker.rating}, expected 4.80.")
        if mukesh_worker.total_jobs_completed != _MUKESH_OVERRIDE["total_jobs_completed"]:
            problems.append("SKW-0066 total_jobs_completed override not applied.")

    federation_admin = session.execute(
        select(Account).where(Account.login_id == "federation_admin")
    ).scalar_one_or_none()
    if federation_admin is None or not verify_password("federation123", federation_admin.password_hash or ""):
        problems.append("federation_admin password hash does not verify.")
    demo_user = session.execute(select(Account).where(Account.login_id == "demo_user")).scalar_one_or_none()
    if demo_user is None or not verify_password("user123", demo_user.password_hash or ""):
        problems.append("demo_user password hash does not verify.")
    mukesh_account = canonical_worker_accounts.get("SKW-0066")
    if mukesh_account is None or not verify_password("skw0066123", mukesh_account.password_hash or ""):
        problems.append("SKW-0066 worker account password hash does not verify.")

    if problems:
        raise SeedValidationError("; ".join(problems))


# ==========================================================================
# Orchestration
# ==========================================================================


@dataclass
class SeedResult:
    federation_id: uuid.UUID
    association_skilled_id: uuid.UUID
    association_general_id: uuid.UUID
    service_count: int
    worker_count: int

    def summary(self) -> str:
        return (
            "Phase 5F demo data seeded successfully: "
            f"1 federation, 2 associations, {self.service_count} services, "
            f"{self.worker_count} workers (+ matching accounts/skills)."
        )


def run_seed(session: Session) -> SeedResult:
    """
    Seed (or reconcile) every Phase 5F demo entity into `session`, and
    validate the result. Does NOT commit or rollback -- that is the
    caller's responsibility (see `main()`), which is what makes this
    function directly reusable from tests against an injected session.
    """
    federation = _get_or_create_federation(session)
    assoc_skilled = _get_or_create_association(
        session,
        association_id=ASSOCIATION_SKILLED_ID,
        name=ASSOCIATION_SKILLED_NAME,
        federation_id=federation.id,
    )
    assoc_general = _get_or_create_association(
        session,
        association_id=ASSOCIATION_GENERAL_ID,
        name=ASSOCIATION_GENERAL_NAME,
        federation_id=federation.id,
    )
    association_id_by_slug = {
        "dhanbad_skilled": assoc_skilled.id,
        "dhanbad_general": assoc_general.id,
    }

    service_ids: dict[str, uuid.UUID] = {}
    for name in SERVICE_CATALOGUE:
        service = _get_or_create_service(session, name)
        session.flush()  # need service.id for WorkerSkill rows below
        service_ids[name] = service.id

    _get_or_create_org_account(
        session,
        login_id="federation_admin",
        password="federation123",
        role=AccountRole.FEDERATION_ADMIN,
        association_id=None,
        federation_id=federation.id,
    )
    _get_or_create_org_account(
        session,
        login_id="dhanbad_skilled",
        password="skilled123",
        role=AccountRole.ASSOCIATION_ADMIN,
        association_id=assoc_skilled.id,
        federation_id=None,
    )
    _get_or_create_org_account(
        session,
        login_id="dhanbad_general",
        password="general123",
        role=AccountRole.ASSOCIATION_ADMIN,
        association_id=assoc_general.id,
        federation_id=None,
    )
    demo_user_account = _get_or_create_org_account(
        session,
        login_id="demo_user",
        password="user123",
        role=AccountRole.USER,
        association_id=None,
        federation_id=None,
    )
    session.flush()  # need demo_user_account.id for its UserProfile
    _get_or_create_user_profile(session, demo_user_account, full_name="Madhav")

    generated_workers = generate_demo_workers()
    for generated in generated_workers:
        association_id = association_id_by_slug[generated.association_slug]
        account = _get_or_create_worker_account(session, generated, association_id)
        session.flush()  # need account.id for the Worker row
        worker = _get_or_create_worker(session, account=account, association_id=association_id, generated=generated)
        session.flush()  # need worker.id for its WorkerSkill rows
        for admin_skill in generated.skills:
            service_name = _SKILL_TO_SERVICE_NAME[admin_skill]
            _ensure_worker_skill(session, worker_id=worker.id, service_id=service_ids[service_name])

    session.flush()
    validate_seed(session, generated_workers)

    return SeedResult(
        federation_id=federation.id,
        association_skilled_id=assoc_skilled.id,
        association_general_id=assoc_general.id,
        service_count=len(service_ids),
        worker_count=len(generated_workers),
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--yes-seed-development",
        action="store_true",
        help="Confirm seeding the resolved (non-test) DATABASE_URL.",
    )
    args = parser.parse_args(argv)

    settings = get_settings()
    try:
        db_name = _check_database_safety(settings.database_url, allow_dev=args.yes_seed_development)
    except SeedSafetyError as exc:
        print(f"Refusing to seed: {exc}", file=sys.stderr)
        return 1

    print(f"Seeding Phase 5F demo data into database '{db_name}'...")
    session = SessionLocal()
    try:
        result = run_seed(session)
        session.commit()
    except Exception as exc:  # noqa: BLE001 - intentionally broad: any failure must roll back
        session.rollback()
        print(f"Seeding failed, rolled back: {exc}", file=sys.stderr)
        return 1
    finally:
        session.close()

    print(result.summary())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
