"""initial domain models

Revision ID: 45f5b1be1f76
Revises:
Create Date: 2026-09-23 15:36:34.194404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f5b1be1f76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # MANUAL ADDITION (reviewed, not part of autogenerate's output): the
    # sequence backing service_requests.request_code's server_default
    # (see app/models/service_request.py::request_code_seq). Autogenerate
    # detected the table/column/index/FK changes below but did NOT emit
    # DDL for this sequence object, even though it is declared on
    # Base.metadata — without this, CREATE TABLE service_requests would
    # succeed (server_default is just stored as text at that point) but
    # every INSERT into service_requests would fail at runtime with
    # "relation request_code_seq does not exist" once nextval() is
    # actually evaluated. Created before service_requests, which is the
    # only thing that references it.
    op.execute("CREATE SEQUENCE IF NOT EXISTS request_code_seq START WITH 1 INCREMENT BY 1")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('associations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('federation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_associations_federation_id', 'associations', ['federation_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'WORKER', 'ASSOCIATION_ADMIN', 'FEDERATION_ADMIN', name='account_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('association_id', sa.UUID(), nullable=True),
    sa.Column('federation_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_index('ix_accounts_association_id', 'accounts', ['association_id'], unique=False)
    op.create_index('ix_accounts_role', 'accounts', ['role'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('workers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('association_id', sa.UUID(), nullable=False),
    sa.Column('worker_code', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='worker_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('worker_code')
    )
    op.create_index('ix_workers_association_id', 'workers', ['association_id'], unique=False)
    op.create_table('service_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_code', sa.String(length=20), server_default=sa.text("'REQ-' || lpad(nextval('request_code_seq')::text, 6, '0')"), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('association_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MATCHING', 'ASSIGNED', 'ACCEPTED', 'WORKER_COMPLETED', 'USER_CONFIRMED', 'PAYMENT_PENDING', 'PAID', 'COMPLETED', 'CANCELLED_BY_USER', name='service_request_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('requested_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_code')
    )
    op.create_index('ix_service_requests_association_id_status', 'service_requests', ['association_id', 'status'], unique=False)
    op.create_index('ix_service_requests_pincode', 'service_requests', ['pincode'], unique=False)
    op.create_index('ix_service_requests_status', 'service_requests', ['status'], unique=False)
    op.create_index('ix_service_requests_user_id', 'service_requests', ['user_id'], unique=False)
    op.create_table('worker_skills',
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('worker_id', 'service_id')
    )
    op.create_index('ix_worker_skills_service_id', 'worker_skills', ['service_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_RESPONSE', 'ACCEPTED', 'DECLINED', 'CANCELLED_BY_WORKER', 'COMPLETED', name='assignment_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_request_id', 'assignments', ['request_id'], unique=False)
    op.create_index('ix_assignments_worker_id_status', 'assignments', ['worker_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assignments_worker_id_status', table_name='assignments')
    op.drop_index('ix_assignments_request_id', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_worker_skills_service_id', table_name='worker_skills')
    op.drop_table('worker_skills')
    op.drop_index('ix_service_requests_user_id', table_name='service_requests')
    op.drop_index('ix_service_requests_status', table_name='service_requests')
    op.drop_index('ix_service_requests_pincode', table_name='service_requests')
    op.drop_index('ix_service_requests_association_id_status', table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_index('ix_workers_association_id', table_name='workers')
    op.drop_table('workers')
    op.drop_table('user_profiles')
    op.drop_index('ix_accounts_role', table_name='accounts')
    op.drop_index('ix_accounts_association_id', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_associations_federation_id', table_name='associations')
    op.drop_table('associations')
    op.drop_table('services')
    op.drop_table('federations')
    # ### end Alembic commands ###

    # MANUAL ADDITION, mirroring the manual upgrade() step above: drop the
    # sequence only after service_requests (its only referencer) is gone.
    op.execute("DROP SEQUENCE IF EXISTS request_code_seq")
