"""add worker leave

Revision ID: a69054875f09
Revises: 0e07ae0cfcff
Create Date: 2026-10-03 09:16:57.962842

Phase 7C-B: pure structural addition -- a brand-new table on a fresh
foreign key, so (unlike 0e07ae0cfcff's add-column-to-an-existing-table
migration) there are no existing rows to backfill and no nullable-first/
backfill/tighten staging is needed. See `app.models.worker_leave` for
what this table does and deliberately does not yet enforce (no minimum
duration, no notice period, no annual quota, no overlap check -- only
the `end_at >= start_at` structural validity constraint).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69054875f09'
down_revision: Union[str, Sequence[str], None] = '0e07ae0cfcff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_leaves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leave_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_at >= start_at', name='ck_worker_leaves_end_at_after_start_at'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_worker_leaves_worker_id', 'worker_leaves', ['worker_id'], unique=False)
    op.create_index('ix_worker_leaves_worker_id_status', 'worker_leaves', ['worker_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_worker_leaves_worker_id_status', table_name='worker_leaves')
    op.drop_index('ix_worker_leaves_worker_id', table_name='worker_leaves')
    op.drop_table('worker_leaves')
    # ### end Alembic commands ###
